Aulas/Aula4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Aula4.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Aulas/Aula4/Controllers/PedidoController.cs
using Aula;
using Aula.Models;
using Aula.Models.PedidoViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace WebApplication.Controllers
{
    public class PedidoController : Controller
    {
        List<Produto> produtos = new List<Produto>() {
            new Produto(1, "produto 1", 49.90m ),
            new Produto(2, "produto 2", 59.90m ),
            new Produto(3, "produto 3", 39.90m ),
            new Produto(4, "produto 4", 129.90m )
        };

        private readonly IDataService _dataService;

        public PedidoController(IDataService dataService)
        {
            this._dataService = dataService;
        }

        public IActionResult Carrossel()
        {
            produtos = this._dataService.GetProdutos();
            return View(produtos);
        }

        [ResponseCache(NoStore=true)]
        public IActionResult Carrinho()
        {
            List<ItemPedido> itensPedido = this._dataService.GetCarrinho();
            return View(new CarrinhoViewModel(itensPedido));
        }

        [ResponseCache(NoStore = true)]
        public IActionResult Resumo()
        {
            List<ItemPedido> itensPedido = this._dataService.GetCarrinho();
            return View(itensPedido);
        }
    }
}

Aulas/Aula4/Views/Pedido/Carrinho.cshtml
@{
    ViewBag.Title = "Carrinho";
}

@model Aula.Models.PedidoViewModels.CarrinhoViewModel
<br />
<br />
<br />
<h3>Meu Carrinho</h3>
<div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-6">item(s)</div>
                <div class="col-md-2 text-center">preço unitário</div>
                <div class="col-md-2 text-center">quantidade</div>
                <div class="col-md-2 text-right">subtotal</div>
            </div>
        </div>
        <div class="panel-body">
            @foreach(var item in Model.ItensCarrinho)
            {
            <div class="row vcenter">
                <div class="col-md-3"><img src="~/images/produtos/small_@(item.Produto.Id).jpg" /></div>
                <div class="col-md-3">@item.Produto.Descricao</div>
                <div class="col-md-2 text-center">R$ @item.PrecoUnitario</div>
                <div class="col-md-2 text-center">@item.Quantidade</div>
                <div class="col-md-2 text-right">R$ @(item.Quantidade * item.PrecoUnitario)</div>
            </div>
            }
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-md-8"></div>
                <div class="col-md-2">Total (@Model.ItensCarrinho.Count() itens)</div>
                <div class="col-md-2 text-right">R$ @Model.Total</div>
            </div>
        </div>
    </div>
    <div class="row">
        <a asp-action="Resumo" 
           asp-controller="Pedido" 
           class="btn btn-success pull-right">
            Finalizar Pedido
        </a>
    </div>
</div>

Aulas/Aula4/Views/Pedido/Carrossel.cshtml
@{
    ViewBag.Title = "Carrossel";
}

@model List<Aula.Models.Produto>
<br />
<br />
<br />
<h3>Catálogo</h3>
<div id="my-carousel" class="carousel slide" data-ride="carousel">
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        @{
            decimal numPaginas = Math.Ceiling((decimal)(Model.Count() / 4.0));
        }

        @for (int pagina = 0; pagina < numPaginas; pagina++)
        {
            var produtos = Model.Skip(pagina * 4).Take(4);
            <div class="item @(pagina == 0 ? "active" : "")">
                <div class="row">
                    @foreach(var produto in produtos)
                    {
                        <a asp-action="Carrinho">
                            <div class="col-md-3">
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <img src="~/images/produtos/large_@(produto.Id).jpg" class="img-responsive" />
                                    </div>
                                    <div class="panel-footer">
                                        <div class="row">
                                            <div class="col-md-8">
                                                @(produto.Descricao)
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-10 col-md-offset-4 pull-right">
                                                <h3>R$ @produto.Preco</h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    }
                </div>
            </div>
        }
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#my-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#my-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>